version: '3.7'

services: 
  user: 
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes: 
      - .:/usr/src/app
    ports: 
      - 5001:5000
    environment: 
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.developmentConfig
    depends_on: 
      - users-db

  users-db:
    build: 
      context: ./project/db
      dockerfile: Dockerfile
    expose: 
      -5432
    environment: 
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=postgres